import Header from "@/components/Header/Header";
import "./scss/index.scss";
import Footer from "@/components/Footer/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const status = true;

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {status ? (
          <AboutLayout>{children}</AboutLayout>
        ) : (
          <UserLayout>{children}</UserLayout>
        )}
      </body>
    </html>
  );
}

export const AboutLayout = ({ children }) => {
  return (
    <>
      <Header />
      {children}
      <Footer />
    </>
  );
};

export const UserLayout = ({ children }) => {
  return (
    <>
      <h1>JAMSHID</h1>
      <h1>SIDEBAR</h1>
      {children}
      <h2>ISLOM</h2>
    </>
  );
};
